---
- name: Remove DBServer Packages 
  hosts: "{{ target_host_name }}*"

  tasks:
  - name: remove mysql server, mysql-python, and ntp
    yum:
      name: "{{ item }}"
      state: absent
    with_items:
      - mariadb-server
      - MySQL-python

  - name: disable mysql port 3306
    firewalld:
      port: "3306/tcp"
      state: disabled
      permanent: true
    notify: restart firewall

  handlers:
  - name: restart firewall 
    service:
      name: firewalld
      state: restarted
...
