---
- name: Remove HAProxy Packages
  hosts: "{{ target_host_name }}*"

  vars:
    - http_port: 80

  tasks:
  - name: remove haproxy
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - haproxy

  - name: remove haproxy config file
    file:
      path: /etc/haproxy/haproxy.cfg
      state: absent      

  - name: disable http port {{ http_port }}
    firewalld:
      port: "{{ http_port }}/tcp"
      state: disabled
      permanent: true
    notify: restart firewall

  handlers:
  - name: restart firewall
    service:
      name: firewalld
      state: restarted          
...
