---
- name: Unsubscribe RHEL Virtual Machine 
  hosts: "{{ target_host_name }}*"
  gather_facts: no
  
  tasks:
  - name: unsubscribe system
    redhat_subscription:
      state: absent 
      username: "{{ redhat_user }}"
      password: "{{ redhat_pass }}"
      pool_ids: "{{ redhat_poolid }}"
...
