---
- name: simple playbook with templates for webserver
  hosts: rhproxy

  tasks:
  - name: remove haproxy
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - haproxy

  - name: disable http port {{ http_port }}
    firewalld:
      port: "{{ http_port }}/tcp"
      state: disables
      permanent: true
    notify: restart firewall

  - name: remove haproxy config file
    file:
      path: /etc/haproxy/haproxy.cfg
      state: absent

  handlers:
  - name: restart firewall
    service:
      name: firewalld
      state: restarted          
...
