---
- name: simple playbook with templates for webserver
  hosts: "{{ vcenter_guest_name }}" 

  vars:
    - http_port: 80
    - ntpserver: 0.nz.pool.ntp.org    

  tasks:
  - name: Install haproxy, ntp packages
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - haproxy
      - ntp

  - name: Ensure ntp, haproxy is enabled at boot and started
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - haproxy
      - ntp

  - name: enable http port {{ http_port }}
    firewalld:
      port: "{{ http_port }}/tcp"
      state: enabled
      permanent: true
    notify: restart firewall

  # Config file has been configured to support dynamic inventory rhtest
  - name: Update haproxy config is the latest
    template:
      src: templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: restart haproxy

  - name: update ntp config
    template:
      src: templates/ntp.conf.j2
      dest: /etc/ntp.conf
    notify: restart ntp

  handlers:
  - name: restart haproxy
    service:
      name: haproxy
    state: restarted
  - name: restart firewall
    service:
      name: firewalld
      state: restarted
  - name: restart ntp
    service:
      name: ntpd
      state: restarted          
...
