---
- name: playbook to create a new rhel7_64 guest from template
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vcenter_vars.yml

  tasks:
  - name: Clone the vCenter RHEL7 template
    vmware_guest:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      name: "{{ vcenter_guest_name }}" 
      guest_id: rhel7_64Guest
      template: "{{ vcenter_template_name }}"
      datacenter: "RedHat Test Environment"
      cluster: "RedHat"
      folder: "/"
      hardware:
        memory_mb: "{{ vcenter_memory }}"
        num_cpus: "{{ vcenter_cpu }}"
      disk:
      - datastore: "RedHat_iSCSI"
        size_gb: "{{ vcenter_disk }}"
        type: thin
      networks:
      - name: "RedHat158"
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost
...
