---
- name: Unsubscribe RHEL Virtual Machine 
  hosts: rhtest
  gather_facts: no
  
  tasks:
  - redhat_subscription:
      state: absent 
      username: "{{ redhat_user }}"
      password: "{{ redhat_pass }}"
    when:
      - name == vcenter_guest_name
...
