---
- name: VMWare Delete Virtual Machine 
  hosts: localhost 
  gather_facts: no
  
  tasks:
  - name: Power off Virtual Machine
    vmware_guest:
      name: "{{ vcenter_guest_name }}"
      datacenter: "RedHat Test Environment"
      cluster: "RedHat"
      state: poweredoff
    delegate_to: localhost

  - name: Delete Virtual Machine
    vmware_guest:
      name: "{{ vcenter_guest_name }}"
      datacenter: "RedHat Test Environment"
      cluster: "RedHat"
      state: absent
    delegate_to: localhost
...
