---
- name: Delete Virtual Machine 
  hosts: rhtest
  gather_facts: no
  
  tasks:
  - name: Unregister RHEL machine
    redhat_subscription:
      state: absent 
      username: "{{ redhat_user }}"
      password: "{{ redhat_pass }}"
    when:
      - name == vcenter_guest_name

  - name: Power off Virtual Machine
    vmware_guest:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      name: "{{ vcenter_guest_name }}"
      datacenter: "RedHat Test Environment"
      cluster: "RedHat"
      state: poweredoff
    when:
      - name == vcenter_guest_name
    delegate_to: localhost

  - name: Delete Virtual Machine
    vmware_guest:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      name: "{{ vcenter_guest_name }}"
      datacenter: "RedHat Test Environment"
      cluster: "RedHat"
      state: absent
    when:
      - name == vcenter_guest_name
    delegate_to: localhost
...
