---
- name: VMWare create a new VM from template
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vcenter_vars.yml

  tasks:
  - name: Clone the vCenter template
    vmware_guest:
      name: "{{ vcenter_guest_name }}" 
      template: "{{ vcenter_template_name }}"
      datacenter: "RedHat Test Environment"
      cluster: "RedHat"
      folder: "/"
      hardware:
        memory_mb: "{{ vcenter_memory }}"
        num_cpus: "{{ vcenter_cpu }}"
      disk:
      - datastore: "RedHat_iSCSI"
        size_gb: "{{ vcenter_disk }}"
        type: thin
      networks:
      - name: "RedHat158"
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost
...
