---
- name: simple playbook with templates for webserver
  hosts: "{{ webserver_host }}"
  gather_facts: no

  tasks:
  - name: get the latest webpage source from git
    git:
      repo: "https://github.com/felizkk/php-website-demo.git"
      dest: "/tmp/websource"
    delegate_to: localhost
  
  - name: update index php file
    template:
      src: "/tmp/websource/website-{{ website_version }}/jinja/index.php.j2"
      dest: "/var/www/html/index.php"

  - name: copy the rest of html files
    copy:
      src: "{{ item }}"
      dest: /var/www/html/
    with_items:
      - "/tmp/websource/website-{{ website_version }}/static/ingram_micro.png"
      - "/tmp/websource/website-{{ website_version }}/static/ansible-tower-small.png"
      - "/tmp/websource/website-{{ website_version }}/static/style.css"
...