---
- name: VMWare change the powerstate of hostgroup VMs
  hosts: "{{ target_host_name }}"
  gather_facts: no

  tasks:
  - name: change state to {{ vcenter_target_state }}
    vmware_guest_powerstate:
      name: "{{ name }}"
      state: "{{ vcenter_target_state }}"
    delegate_to: localhost
...