---
- name: VMWare create snapshots of VMs under a host group
  hosts: "{{ target_host_name }}"
  gather_facts: no

  tasks:
  # This playbook maintains a single snapshot
  # So the flow is to remove old one first before creating a new one
  # datacenter parameter is required
  - name: remove old snapshot
    vmware_guest_snapshot:
      datacenter: "{{ vcenter_datacenter_name }}"
      folder: "{{ vcenter_folder_name }}"
      name: "{{ name }}"
      snapshot_name: "{{ vcenter_snapshot_name }}"
      state: absent
    delegate_to: localhost

  - name: create new snapshot
    vmware_guest_snapshot:
      datacenter: "{{ vcenter_datacenter_name }}"
      folder: "{{ vcenter_folder_name }}"
      name: "{{ name }}"
      snapshot_name: "{{ vcenter_snapshot_name }}"
      state: present
    delegate_to: localhost
...