---
- name: VMWare delete a VM
  hosts: localhost 
  gather_facts: no
  
  tasks:
  - name: power off VM
    vmware_guest:
      name: "{{ target_host_name }}"
      datacenter: "{{ vcenter_datacenter_name }}"
      cluster: "{{ vcenter_cluster_name }}"
      state: poweredoff
    delegate_to: localhost

  - name: delete VM
    vmware_guest:
      name: "{{ target_host_name }}"
      datacenter: "{{ vcenter_datacenter_name }}"
      cluster: "{{ vcenter_cluster_name }}"
      state: absent
    delegate_to: localhost
...
