---
- name: Windows Server Simple Playbook Demo
  hosts: "{{ target_host_name }}*"

  tasks:
  # Setting up dummy registry entries
  - name: Create registry path MyCompanySoftware
    win_regedit:
      path: HKCU:\Software\MyCompanySoftware  
  - name: Add or update registry path MyCompanySoftware, with entry 'name'
    win_regedit:
      path: HKCU:\Software\MyCompanySoftware
      name: name
      data: felizkarnadi
  - name: Add or update registry path MyCompanySoftware, with entry 'employeeid'
    win_regedit:
      path: HKCU:\Software\MyCompanySoftware
      name: employeeid
      data: 113355

  # Install MSI for 7Zip
  - name: create installer directory
    win_file:
      path: C:\installer
      state: directory
  - name: download the 7-Zip package
    win_get_url:
      url: https://www.7-zip.org/a/7z1805-x64.msi
      dest: C:\installer\7z.msi
  - name: ensure 7-Zip is installed via win_package
    win_package:
      path: C:\installer\7z.msi
      state: present

  # Install/Update Firefox using Chocolatey.org package manager
  # Chocolatey is going to be auto-installed if not present
  - name: install Firefox using Chocolatey.org
    win_chocolatey:
      name: firefox
      state: latest

  # Firewall Rule to enable RDP
  - name: Enable Windows Firewall Rule 
    win_firewall_rule:
      name: Remote Desktop
      localport: 3389
      protocol: tcp
      action: allow
      direction: in
      profiles: private
      state: present
      enabled: yes

  # Enable Spooler Service
  - name: Set service startup mode to auto and ensure it is started
    win_service:
      name: spooler
      start_mode: auto
      state: started
...